# SPDX-License-Identifier: GPL-3.0-or-later
"""Derive a scoped report from immutable search, full-suite and holdout records."""
import json
from pathlib import Path
import sys
import hashlib
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

ROOT=Path(__file__).resolve().parents[1]

def load(p):return json.loads((ROOT/p).read_text())
def link(id_):return f'[{id_}](../results/runs/{id_}/results.json)'
def num(v,scale=1):return 'unknown' if v is None else f'{v*scale:.4g}'

def render(batch):
    data=load(batch/'evaluation.json'); search=load(batch/'search.json')['experiments']
    proposals={f:load(Path('results/runs')/e/'optimization.json') for f,e in search.items()}
    realization=load(batch/'realization.json')['children']
    ids=list(data['baseline_experiments'].values())+[r['experiment'] for r in data['continuous'].values()]+[r['experiment'] for r in data['children'].values()]
    records={id_:load(Path('results/runs')/id_/'results.json') for id_ in ids}
    suites={r['suite_sha256'] for r in records.values()}; specs={r['spec_sha256'] for r in records.values()}
    assert len(suites)==len(specs)==1 and data['source_unchanged']
    assert not any(r['eligible'] for r in records.values())
    def m(r,check,key):return r['checks'][check]['metrics'].get(key)
    text=['# Robust optimization research — 9 October 2026\n',
          'M100 Meridian MIC-34-M/MIC-34-C, Arienne Audio Flat K47 Cardioid/Omni K47FRB, realistic P48. **All implementations remain unqualified.** This is restricted, model-conditional response optimization: the prerequisite audit found no complete validated semiconductor/noise/process set permitting an architectural performance ranking. No production topology, PCB or prototype is selected. No purchase, supplier contact, licence acceptance or external publication occurred.\n',
          '[Contract](../CONTRACT.md) · [specification](../spec/microphone_spec.yaml) · [capsule uncertainties](../spec/capsule_model.yaml) · [model validity](device_model_validation.md) · [first batch](first_architecture_batch.md) · [dated decisions](robust_optimization_decisions.md). Physics/measurements → SPICE → tests → numerical optimization → engineering reasoning → LLM intuition.\n',
          '## Prerequisites and scope\n',
          'JFE150 and authored BC846B permit falsifiable nominal hypotheses within the library’s documented discrepancies, not a production-bounded response/noise prediction. OPA197’s grounded small-signal agreement does not validate these floating integrations. Carrier ordinary AC/stationary-noise objectives are blocked. `noise`, `distortion`, `headroom`, `loading`, `balance`, `drive`, `current` and `complexity` remain separate objective interfaces; missing behavior prerequisites block the corresponding optimization axis. No weighted engineering/cost winner score exists. Legacy noise optimization is restricted to the ideal infrastructure fixture.\n',
          'The active numerical axis is maximum response deviation over nominal and two supply/feed training scenarios. DC current, positive rail/polarization and energy closure are hard feasibility gates; each trained scenario must also satisfy the unchanged 1 dB response limit before a proposal can be called screen-feasible. Search from outside that region uses response itself, without an arbitrary weighted penalty. No safe capsule voltage, absolute system noise, polar pattern or mechanical SPL rating is inferred.\n',
          '## Budget, parameters and termination\n',
          '[Predeclared plan](../optimization/robust_plan.yaml) gives every one of six mechanisms 12 unique design-vector evaluations, three scenarios each. Prerequisite/integration holds leave unused budget visible. Sources and every implementation file freeze before each run; individual trials never edit canonical parents. [Batch plan](../'+str(batch/'plan.json')+') and [search index](../'+str(batch/'search.json')+') preserve the actual allocation.\n',
          'Bounds: JFET output C 47–188 µF per leg; CMOS guard uses the same output bracket, CMOS feedback 50–200 pF, BJT feedback 100 pF–100 nF. The plan records physically motivated current/bias/servo/guard/carrier hypotheses deferred on missing model/loop evidence. Design bounds are separate from unchanged acceptance/uncertainty ranges. Passive tolerances recenter around a continuous design without shrinking their relative widths; an independent regression rejects narrowing. No polarization parameter was optimized.\n',
          '| Family | Evaluations / reserved | Scenario attempts / errors | Runtime s | Outcome |\n| --- | ---: | ---: | ---: | --- |']
    for family,r in proposals.items():
        text.append(f'| {family} | {r["evaluations"]} / {r["budget_declared_before_run"]} | {r["scenario_attempts"]} / {r["analysis_errors"]} | {r["runtime_s"]:.2f} | [{r["termination"]}](../results/runs/{r["experiment_id"]}/optimization.json) |')
    text+=['\nThree supported families used their whole budgets; none converged. The BJT result is “no feasible tested point”, not a proof that the entire value region is empty. CMOS holds preserve all six rejected scenario analyses. Seed 34047 generated numerical proposals. Further effort follows 20 explicitly reserved 50/25/15/10 slots: 10 improvement (eight discrete combinations plus two validation tasks), one of five underexplored tasks executed, zero of three new-concept tasks executed, two assumption-breaking hypotheses tested across combinations. Four underexplored and three new-concept tasks remain held on prerequisites; they were not reassigned to the favored family. All 14 catalogue families remain alive.\n',
           '## Continuous proposals and withheld uncertainty\n',
           '| Family | Baseline nominal deviation dB | Continuous C µF/leg | Continuous nominal / trained worst dB | Withheld corner worst dB | Independent random DC/AC passes |\n| --- | ---: | ---: | ---: | ---: | --- |']
    for family,entry in data['continuous'].items():
        base=records[data['baseline_experiments'][family]];r=records[entry['experiment']];v=load(Path(entry['validation']));s=v['random_summary'];p=proposals[family]
        text.append(f'| {family} | {num(m(base,"frequency_response","response_deviation_db"))} | {num(p["best"]["design_values"]["OUTPUT_C"],1e6)} | {num(m(r,"frequency_response","response_deviation_db"))} / {num(p["best"]["objective"]["value"])} | {num(v["corner_summary"]["worst_observed"])} | {s["passing"]}/{s["samples"]}; 95% sampler interval [{num(s["binomial_95_interval"][0])}, {num(s["binomial_95_interval"][1])}] |')
    text+=['\nEach continuous proposal has a complete applicable suite, 40 additional documented DC/AC cases and 16 independent seed-84047 cases, with exact records linked below. Withheld cases include one-at-a-time capsule/interface endpoints, cross capacitance 0–5 pF, correlated combined passive/endpoints, full −10/+50°C model laws, documented resistor tolerance/TCR endpoints and complete JFE vendor weak/strong files. The vendor corners have known library limit failures: they are coupled proposal stresses, not certified manufacturer coverage. No BETA/VTO/BF/IS/noise terms were independently randomized, and the uncovered manufacturer/JFE bounds remain unchanged.\n',
           'All finite adverse pass/fail specimens remain in worst/percentile summaries; missing/error analyses stay in denominators and invalidate robust objectives. Random draws are artificial uniform/log-uniform scenario designs, not measured production distributions. Binomial intervals describe only that sampler’s DC/AC screen; deterministic corners have no binomial interpretation. Nonparametric 95th-percentile metric intervals retain an unbounded upper endpoint at n=16; missing analyses would make the interval incomplete. Even 16/16 cannot establish 99.9% yield.\n',
           'Random cases in this first batch are not pair-matched across implementations: differing passive counts consume different portions of the RNG stream. Their pass fractions must not be used to rank families or capacitor combinations. Common deterministic endpoints provide the controlled sensitivity comparison. All-requirement yield, semiconductor joint process/noise distributions, full-corner noise/distortion, loop return ratio/Nyquist, device SOA and physical evidence remain absent.\n']
    for family,e in data['continuous'].items():
        text.append(f'- {family}: {link(data["baseline_experiments"][family])} → {link(e["experiment"])}; [withheld raw-case/interval record](../{e["validation"]}).')
    text+=['\n## Actual BOM combinations and full-suite outcomes\n',
           '[Realizations](../'+str(batch/'realization.json')+') preserve continuous proposal ancestry. Each leg uses one to four individual Panasonic EEU-FR1J470, 47 µF ±20%, 63 V radial parts, each with independent capacitance and explicit loss/leakage controls. [Primary observations](architecture_sources/robust_observations_2026-10-09.json) and [dated procurement](procurement/robust_parts_2026-10-09.yaml) separate manufacturer limits from indexed order observations.\n',
           'FR-A DF ≤0.09 at 120 Hz/20°C gives a constant-series-loss stress of 2.540 Ω per 47 µF part; 63 V/29.6 µA gives 2.128 MΩ ohmic leakage stress. These conversions are explicit engineering scenarios, not a broadband ESR or real bias/temperature leakage/noise model. Each branch includes resistor Johnson noise in SPICE; dielectric/voltage/aging/excess-noise laws and layout inductance remain unknown. Temperature/TCR cases do not cure those gaps. Procurement/build qualification stays held.\n',
           '| Realized child | Parent niche | 47 µF per leg | Nominal deviation dB | Delta from continuous parent dB | Withheld worst dB | Random passes /16 | Installed components | Priced electronics net EUR scenario |\n| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |']
    plotted={}
    for child in realization:
        id_=child['candidate'];entry=data['children'][id_];r=records[entry['experiment']];v=load(Path(entry['validation']));b=__import__('yaml').safe_load((ROOT/'candidates'/id_/'bom.yaml').read_text())
        nominal=m(r,'frequency_response','response_deviation_db')
        parent_nom=m(records[data['continuous'][child['family']]['experiment']],'frequency_response','response_deviation_db') if child['family'] in data['continuous'] else None
        delta=nominal-parent_nom if nominal is not None and parent_nom is not None else None
        text.append(f'| [{id_}](../candidates/{id_}/bom.yaml) | {child["family"]} | {child.get("count_per_leg","series Cf")} | {num(nominal)} | {num(delta)} | {num(v["corner_summary"]["worst_observed"])} | {v["random_summary"]["passing"]} | {sum(p["quantity"] for p in b["physical_parts"])} | {num(b["electronics_cost"]["priced_items_net_eur_scenario"])} |')
        if 'count_per_leg' in child:plotted.setdefault(child['family'],[]).append((child['count_per_leg'],nominal,v['corner_summary']['worst_observed']))
    text+=['\nEvery child receives the full 14-check suite plus seed-94047 DC/AC validation; all remain failed or incomplete. Individual tests/statuses, missing evidence, exact device hashes, decks and all parent metric deltas are in the [evaluation index](../'+str(batch/'evaluation.json')+'). Full-suite metadata/spec/source cohort matches for all baseline/continuous/realized comparisons; the earlier optimizer cohort differs because realization sources were added between idle phases. No ideal-parent result is attributed to a BOM child.\n',
           'The series-feedback BJT child candidate_0024 preserves its fixed 500 kΩ reset and adds a documented 100 pF C0G in series with the original 100 nF, including DF/IR controls. It is a budgeted structural hypothesis, not a threshold change, trimming or blanket no-FET rejection. Its exact current/noise/nonlinear/process limitations stay in its record.\n',
           '![Nominal improvement and adverse endpoint failures](robust_optimization_response.png)\n',
           '## Family-specific implications and next experiments\n',
           '1. Conventional JFET: output-capacitance tuning improves the modeled LF response; finite output impedance/balance, noise-model validity and nonlinear/startup failures still prevent advancement. Low capsule-leakage-resistance stress sharply defeats response. Measure/validate the capsule leakage and the JFE operating point under that load before extending value search. Keep the filtered-input niche as a research representative.\n',
           '2. Servo JFET: lower nominal/trained response deviation does not establish better robustness. Common low-leakage and parasitic endpoints expose servo/bias sensitivity; complete audio/DC return-ratio and bias-authority controls are more informative than another resistor search. Its distinct niche is retained.\n',
           '3. BJT-only charge: the best tested continuous feedback C is about '+num(proposals['no_fet']['diagnostic_best_infeasible']['design_values']['FEEDBACK_C'],1e9)+' nF, with trained deviation '+num(proposals['no_fet']['diagnostic_best_infeasible']['objective']['value'])+' dB. Fixed reset/base-current authority, charge gain and finite-loop loading remain coupled limiting hypotheses. Retain the series-capacitor child’s actual failure; independently test transfer with analytic reset/charge oracles and obtain bipolar 1/f/current-noise evidence before further structural work.\n',
           '4. Guarded CMOS and CMOS charge: stop numerical value tuning on the repeatable integration failure. The fastest useful experiment is a separate realistic floating-rail macro DC/current/common-mode harness, preserving the current failed integrations and manufacturer models. No physical-family rejection follows.\n',
           '5. Carrier: preserve deterministic sideband controls, failed P48 integration and all unscreened feature holds. Establish physical oscillator/mixer power and validated periodic stochastic noise/extraction before comparable objective search. Ordinary stationary SPICE noise would be incompatible evidence.\n',
           'Cross-family response order is uncertainty-sensitive: servo has the smaller nominal deviation, whereas individual parasitic/load endpoints and different artificial draws can change the apparent order. The shared low-leakage endpoint fails both. These are model sensitivity observations, not a supported production ranking. No single production winner is declared.\n',
           '## Procurement, patent and physical gates\n',
           'Use one capsule for one finished microphone. Count every installed capacitor and unavoidable pack excess, retain intended quantities, retail MOQ1 and indexed freshness separately from the manufacturer’s 5000-piece packaging. New capacitor stock observation is four months old and live retrieval failed. Exact lead/dispatch, some existing semiconductor/passive orderability, TME shipping, tax basis and import/payment fees remain unresolved.\n',
           'All confirmed German delivered totals remain **null**. Priced net electronics subtotals use documented quantity-one shelf observations as conservative scenarios; extra parallel parts cost EUR0.40 net each in that scenario. Parent EUR25/29.75 shipping-tax alternatives apply once to the DigiKey basket, not once per part. Unknown parts/other seller shipping/fees are not zero. Capsule, body, PCB, XLR/protection and mechanics are excluded. No numerical spending cap, hypothetical bulk price or cost/performance scalar is introduced. Different quantities are alternatives, never a comparison-purchase bundle.\n',
           '[New candidate-linked patent flags](patents/robust_optimization_2026-10-09.yaml) carry original affected features, circuit hashes, ancestry, DE/applicable EP scope and prototype/manufacture/build-publication holds. Claims and official status remain unscreened; no blocking claim or legal clearance is invented. Parallel/series passives and numerical values do not establish a design-around. Required claim/territory/current official-status review and professional resolution of material uncertainty precede any held gate. No prototype or implementation publication is authorized.\n',
           'Evidence states remain separate: nominal DC/AC screen feasibility demonstrated for some proposals; finite scenario failures demonstrated; statistically supported manufacturing evidence absent; physical qualification absent. Safe capsule polarization, acoustic noise/overload/polar patterns and MIC-34-M/MIC-34-C physical variant behavior remain unknown.\n',
           '## Checks and preservation\n',
           '57 laboratory regressions passed before this batch, including missing-noise/periodic gates, adverse specimens, strict budgets, unchanged capsule uncertainty, design-tolerance non-narrowing, complete coupled corner rendering and an independent parallel-capacitance oracle. One early 51-pass/one-failure verification and the repaired successors remain; an initial driver import failure is preserved in [its probe](probes/robust_driver_import_2026-10-09/failure.log). [Integrity](robust_optimization_integrity_2026-10-09.json) and [private recovery receipt](robust_optimization_preservation_2026-10-09.json) record final hash, inventory, restore and repository checks.\n',
           'Original failures, raw data, seeds, parent links and exact source/model/spec cohorts are preserved. Archive/Pareto views retain per-cohort response/current niche representatives without promoting unvalidated noise/yield or incomplete cost into production champions. Independent persistent backup coverage and 89 declared missing legacy source originals remain incomplete; local capture/restore is recovery evidence only.\n']
    (ROOT/'research/robust_optimization_report.md').write_text('\n'.join(text)+'\n')
    fig,axes=plt.subplots(1,2,figsize=(10,4),layout='constrained')
    for family,points in plotted.items():
        points.sort();label='Conventional JFET' if family=='conventional_jfet' else 'Servo JFET'
        axes[0].plot([p[0] for p in points],[p[1] for p in points],marker='o',label=label)
        axes[1].plot([p[0] for p in points],[p[2] for p in points],marker='o',label=label)
    for ax,title in zip(axes,['Nominal response screen','Worst withheld finite scenario']):
        ax.axhline(1,color='grey',linestyle='--',label='Frozen 1 dB limit');ax.set_title(title);ax.set_xlabel('47 µF capacitors per output leg');ax.set_ylabel('Response deviation (dB)');ax.set_xticks([1,2,3,4]);ax.grid(alpha=.2)
    axes[0].legend(fontsize=8);fig.suptitle('Model-conditional response; every BOM remains unqualified',fontsize=12)
    fig.savefig(ROOT/'research/robust_optimization_response.png',dpi=160);plt.close(fig)
    (ROOT/'research/robust_optimization_plot_provenance.json').write_text(json.dumps({'input_sha256':{str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [ROOT/batch/'evaluation.json',*[ROOT/'results/runs'/id_/'results.json' for id_ in ids]]},'suite_sha256':list(suites),'spec_sha256':list(specs),'production_winner':None},indent=2)+'\n')

if __name__=='__main__':render(Path(sys.argv[1]))
